### DISCUSSION TITLE
Is test 5.6 incomplete?

### DISCUSSION THREAD

**Discussion by jvleminc** [alivx/CIS-Ubuntu-20.04-Ansible#14] [General]
Not sure if placing the `root` user in the `sudo` group is sufficient to restrict `su` access.
```
# 5.6 Ensure access to the su command is restricted
# Restricting the use of su , and using sudo in its place, provides system administrators better control of the escalation of user privileges to execute privileged commands. The sudo utility also provides a better logging and audit mechanism, as it can log each command executed via sudo , whereas su can only record that a user executed the su program.
- name: 5.6 Ensure access to the su command is restricted
  user:
    name: "root"
    groups: ["sudo"]
```

Other manuals state:
_Solution: Create an empty group that will be specified for use of the su command. The group should be named according to site policy._

`groupadd sugroup`

_Add the following line to the /etc/pam.d/su file, specifying the empty group:_

`auth required pam_wheel.so use_uid group=sugroup`
