### DISCUSSION TITLE
Improve test 1.5.3

### DISCUSSION THREAD

**Discussion by jvleminc** [alivx/CIS-Ubuntu-20.04-Ansible#16] [General]
Actually test 1.5.3 is DIY. We could implement this test by something similar to the following:

```
- name: 1.5.3 Ensure authentication required for single user mode
  block:
    - name: 1.5.3 Ensure authentication required for single user mode - step 1
      shell: /bin/grep -e "^root:[\*]:" /etc/shadow | /usr/bin/awk 'END {if (NR == 0) print "pass" ; else print "fail"}'
      register: result
      ignore_errors: true

    - name: 1.5.3 Ensure authentication required for single user mode - step 2
      # bash must be used or mysterious errors are thrown
      shell: "/bin/bash -c 'echo -e {{ root_password }} | passwd root'"
      when: result.stdout == "fail"
```
with `root_password` defined by the user (or a default password in `main.yml`).

What do you think?
