### DISCUSSION TITLE
What is the idea of the first part of 3.5.1.7?

### DISCUSSION THREAD

**Discussion by jvleminc** [alivx/CIS-Ubuntu-20.04-Ansible#40] [General]
Not sure what the idea is behind these lines in the "Ensure default deny firewall policy" policy.
```
    - name: 3.5.1.7 Ensure default deny firewall policy
      shell: |
        ufw allow git
        ufw allow in http
        ufw allow in https
        ufw logging on
```

If any ports need to be opened, this can be done in the last part of 3.5.1.6:
```
    - name:
      ufw:
        rule: "{{ item.rule }}"
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
      with_items: "{{ list_of_ports_to_allow }}"
```

If you agree, I will create a PR to remove that first part, @alivx .
