### ISSUE TITLE
paramater error on task 1.7.1.2

### ISSUE THREAD

**Issue by samqi** [alivx/CIS-Ubuntu-20.04-Ansible#1]
```
TASK [CIS-Ubuntu-20.04-Ansible : 1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration] ************************************************************************************************************
fatal: [192.168.x.x]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (replace) module: follow Supported parameters include: after, attributes, backup, before, encoding, group, mode, owner, path, regexp, replace, selevel, serole, setype, seuser, unsafe_writes, validate"}
```

**Comment by alivx** [comment]
Can you please share with me the OS version and name

**Comment by samqi** [comment]
$ cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by jvleminc** [comment]
This test runs fine in my setup as well. 

I believe this error is due to the use of an older `ansible` version, that doesn't support the `follow` keyword:
```
Unsupported parameters for (replace) module: follow
```

The task itself:
```
    - name: 1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration
      replace:
        dest: /etc/default/grub
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.*apparmor)\"[^\"]*)(\".*)'
        replace: '\1 apparmor=1 security=apparmor\2'
        follow: true    <-----------------------------------------------------
      register: output_1_7_1_2
```

Can OP check with `ansible 2.9.16`?

```
ansible --version
ansible 2.9.16
```
