### ISSUE TITLE
Error while running the comamnd

### ISSUE THREAD

**Issue by contactjegan** [alivx/CIS-Ubuntu-20.04-Ansible#24]
ERROR! the role 'CIS-Ubuntu-20.04-Ansible' was not found in /opt/hardening/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/opt/hardening

The error appears to be in '/opt/hardening/run.yaml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - { role: "CIS-Ubuntu-20.04-Ansible" }
      ^ here
This one looks easy to fix. It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote. For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

**Comment by alivx** [comment]
Try the below:
```
cd /srv/;clone  https://github.com/alivx/CIS-Ubuntu-20.04-Ansible.git
```

put your `run.yaml` under `/srv/`

Then run your playbook.

Note:
Content of run.yaml should be like this

```
---
- hosts: 127.0.0.1
    connection: local
    become: yes
    remote_user: root
    gather_facts: no
    roles:
        - { role: "CIS-Ubuntu-20.04-Ansible" }
```
